App:
  Url: http://localhost:9999
  Workdir: ./
  # local,production,test
  Env: local
  Cluster: false
  Secret: 3123dhwahduwad
Rpc:
  Open: false
  Port: 8888
Etcd:
  Host: [chat-etcd-1:2379]
  BasePath: chat
Mysql:
  Database: customer_service
  Username: root
  Password: zyz22222
  Port: 3306
  Host: 121.196.110.77
Redis:
  Addr: 121.196.110.77:6379
  Auth: zyz22222
  Db: 0
Http:
  Host: 0.0.0.0
  Port: 9999
File:
  Storage: local
  QiniuAk:
  QiniuSK:
  QiniuUrl:
  QiniuBucket: weilvtest
Wechat:
  MiniProgramAppId:
  MiniProgramAppSecret:
  SubscribeTemplateIdOne:
