version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: chat-nginx
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./services/nginx/ssl:/ssl:rw
      - ./services/nginx/conf.d:/etc/nginx/conf.d/:rw
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx/:rw
    restart: always
    networks:
      - default
 
  go:
    build:
      context: ..
      dockerfile: ./docker-compose/services/go/Dockerfile
    container_name: go
    expose:
      - 8080
      - 8081
    restart: always
    networks:
      - default

networks:
  default:
